# Generated by Django 2.2 on 2019-04-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_date', models.DateField()),
                ('number_of_frames', models.IntegerField()),
                ('annual_production', models.IntegerField()),
                ('last_harvested', models.DateField()),
                ('number_of_bees', models.IntegerField()),
                ('image', models.CharField(max_length=400)),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='hive_app.Keeper')),
            ],
        ),
        migrations.CreateModel(
            name='Bee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=400)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bees', to='hive_app.Hive')),
            ],
        ),
    ]
