# Generated by Django 2.2 on 2019-04-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='name',
            field=models.CharField(default='Hive Name', max_length=100),
        ),
    ]
